export const SERVICES_DATA = [
  {
    id: 1,
    price: 12,
    name: "Elite Home Cleaning",
    image:
      "https://bookdirtbusters.com/wp-content/uploads/2020/10/house-cleaning-service.jpeg",
    address: "Gulberg, Lahore",
    timing: "08:00 AM - 10:00 PM",
    distance: "4km",
    free: false,
    ad: true,
    category: "Home Cleaning",
  },
  {
    id: 2,
    price: 34,
    name: "QuickFix Repair Services",
    image: "https://www.westcoastappliance.ca/img/service.jpg",
    address: "Al Qurm, Muscat",
    timing: "09:00 AM - 06:00 PM",
    distance: "5km",
    free: true,
    ad: false,
    category: "Repairing",
  },
  {
    id: 3,
    price: 34,
    name: "Premium Painting Solutions",
    image:
      "https://tanjongpagar.lshandymansingapore.com/wp-content/uploads/2019/05/painting-service.jpg",
    address: "Bahria Town, Karachi",
    timing: "07:00 AM - 08:00 PM",
    distance: "3.5km",
    free: false,
    ad: true,
    category: "Painting",
  },
  {
    id: 4,
    price: 54,
    name: "Shiny Cleaners",
    image:
      "https://5.imimg.com/data5/SELLER/Default/2022/9/JD/WZ/ZK/15827034/home-housekeeping-services-500x500.jpg",
    address: "Al Khuwair, Muscat",
    timing: "08:30 AM - 09:30 PM",
    distance: "6km",
    free: true,
    ad: false,
    category: "Home Cleaning",
  },
  {
    id: 5,
    price: 32,
    name: "Repair King",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTL_ZWbdAxRLqlgdphFZGD-g9ZHRCtvOWntzQ&s",
    address: "DHA Phase 5, Lahore",
    timing: "10:00 AM - 08:00 PM",
    distance: "2km",
    free: false,
    ad: true,
    category: "Repairing",
  },
  {
    id: 6,
    price: 76,
    name: "Pro Painters",
    image:
      "https://www.hammerandbrush.com.au/wp-content/uploads/2021/09/house-painters-at-work-5662561-1024x683.jpg",
    address: "Seeb, Muscat",
    timing: "09:00 AM - 07:00 PM",
    distance: "4.5km",
    free: true,
    ad: false,
    category: "Painting",
  },
  {
    id: 7,
    price: 39,
    name: "Home Care Cleaning",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSV1-hqunVnSMVm0HrNUiJf2H_yo_IkjtLxJg&shttps://images.ctfassets.net/8x7sonz8wgp8/20Jvcg8l6AZd8BkRO9z80/a9d5bbbe7b0502dbb88e9620c2dec8f6/blog-img--a-man-cleaning-car-front-dash.jpg",
    address: "Johar Town, Lahore",
    timing: "08:00 AM - 09:00 PM",
    distance: "3km",
    free: true,
    ad: false,
    category: "Home Cleaning",
  },
  {
    id: 8,
    price: 92,
    name: "Master Repair Services",
    image:
      "https://static.vecteezy.com/system/resources/previews/006/972/908/large_2x/mobile-phone-repairing-the-master-remotes-the-mobile-phone-using-tools-on-a-special-mat-flat-lay-top-view-photo.jpg",
    address: "Ruwi, Muscat",
    timing: "07:30 AM - 05:30 PM",
    distance: "7km",
    free: false,
    ad: true,
    category: "Repairing",
  },
];
