export const ALL_ORDER_HISTORY = [
  {
    id: "1",
    title: "Woodlands Hills Salon",
    location: "Keira Throughway",
    distance: "5.0 Kms",
    services: "Haircut x 1 + Shave x 1",
    date: "8 Mar 2021",
    price: "$102",
  },
  {
    id: "2",
    title: "Urban Cuts Studio",
    location: "Bakersfield Avenue",
    distance: "8.2 Kms",
    services: "Haircut x 1",
    date: "15 Feb 2021",
    price: "$75",
  },
  {
    id: "3",
    title: "Luxury Spa and Salon",
    location: "Madison Park",
    distance: "3.5 Kms",
    services: "Full Body Massage x 1",
    date: "21 Apr 2021",
    price: "$150",
  },
  {
    id: "4",
    title: "Elegant Hair Lounge",
    location: "Liberty Plaza",
    distance: "6.7 Kms",
    services: "Haircut x 1 + Hair Color x 1",
    date: "30 Jan 2021",
    price: "$120",
  },
  {
    id: "5",
    title: "Gents Grooming Hub",
    location: "Ocean Drive",
    distance: "4.3 Kms",
    services: "Shave x 1 + Beard Trim x 1",
    date: "10 Dec 2020",
    price: "$50",
  },
];
