import * as colors from "./colors";

export const themeLight = {
  dark: false,
  colors: {
    primary: colors.primaryBlue,
    secondary: colors.lightprimary,
    background: colors.white,
    background2: colors.gray8,
    card: colors.white,
    text: colors.gray5,
    border: colors.gray2,
    error: colors.red,
    success: colors.green,
    warning: colors.orange,
    waiting: colors.yellow,
    disable: colors.gray6,
    secondaryCard: colors.gray1,
    secondaryBorder: colors.gray1,
    secondaryBackground: colors.lightNavyBlue,
    thirdBackground: colors.gray2,
    forthBackground: colors.gray1,
    secondaryText: "#C9C9C9",
    thirdText: colors.gray3,
    modal: colors.white,
    key: colors.black,
    notification: colors.green,
  },
};

export const themeDark = {
  dark: true,
  colors: {
    primary: colors.primaryBlue,
    secondary: colors.lightBlue,
    background: colors.black,
    background2: colors.gray7,
    card: colors.black,
    text: colors.gray1,
    border: colors.gray3,
    error: colors.red,
    success: colors.green,
    warning: colors.orange,
    waiting: colors.yellow,
    disable: colors.gray3,
    secondaryCard: colors.gray4,
    secondaryBorder: colors.gray4,
    secondaryBackground: colors.gray5,
    thirdBackground: colors.gray3,
    secondaryText: colors.gray2,
    forthBackground: colors.gray5,
    thirdText: colors.gray3,
    modal: colors.gray5,
    key: colors.black,
  },
};
